### ISSUE TITLE
Expo version update to V52 caused errors

### ISSUE THREAD

**Issue by itaybarber** [adrianhajdin/uber#13]
1. When trying to load the app the first time -> Error: Use process(css).then(cb) to work with async plugins. Solved by changing  "tailwindcss": "3.3.2",
2.  (NOBRIDGE) ERROR  Warning: Error: Couldn't find a screen named 'index' to use as 'initialRouteName' - Still didn't manage to fix

**Comment by alphayowakarindi** [comment]
@itaybarber Changing initialRouteName to 'home' worked for me.

**Comment by alphayowakarindi** [comment]
> 2. (NOBRIDGE) ERROR  Warning: Error: Couldn't find a screen named 'index' to use as 'initialRouteName' - Still didn't manage to fix

Changing initialRouteName to 'home' worked for me.
